### ISSUE TITLE
wrong detection resource instead of resources for irregular noum i.e. 'menu'

### ISSUE THREAD

**Issue by cs3b** [puffer/puffer#20]
when:

```
resources :menu, :controller => 'menu'
```

then

```
No route matches {:puffer_scope=>:admin, :puffer=>3, :action=>"show", :controller=>"admin/menu"}
```

**Comment by pyromaniac** [comment]
What version do you use? Try maste head. I think it should work - 
https://github.com/puffer/puffer/blob/master/lib/puffer/resource/routing.rb#L9
https://github.com/puffer/puffer/blob/master/lib/puffer/resource/node.rb#L62
