### ISSUE TITLE
a lot problems using nested models

### ISSUE THREAD

**Issue by cs3b** [puffer/puffer#21]
like

```
 Cms::Page
```
- it have problems with filters
- resource path are not calculated properly ( using resources_path for all )

sorry, but giving up ( to many problems I've encountered ) and I think - it's my personal opinion - that your way of building this solution is not accurate to problem ( to much custom magic code, that is very hard to overwrite). The way that inherited_resources solve problem of routing and handling resource (helpers that they use) is much better.

Wish you look but, try to look at different existing solution for small particular problems that you are trying to solve.

**Comment by pyromaniac** [comment]
let's see. As i suposed, models nesting should not affect controllers nesting. I think, you should try to create

```
class Cms::PagesController
  setup do
    model_name :'cms/page'
  end
end
```

Please, let me know if it helps.

Also, please use master head source.
