### ISSUE TITLE
problem with admin session

### ISSUE THREAD

**Issue by cs3b** [puffer/puffer#22]
trying 595726e81d6f5d84c0efd0cb5076f47be62de9bf getting

``` erb
Started GET "/admin/session/new" for 127.0.0.1 at 2011-11-09 11:38:37 +0100
  Processing by Admin::SessionsController#new as HTML
  Parameters: {"puffer_scope"=>:admin, "puffer"=>session}
Rendered /home/mc/.rvm/gems/ruby-1.9.3-p0@surveycom/bundler/gems/puffer-595726e81d6f/app/views/puffer/sessions_base/new.html.erb within layouts/puffer_sessions (19.8ms)
Completed 500 Internal Server Error in 110ms

ActionView::Template::Error (The action 'create' could not be found for StringComponent):
    1: <%= form_for record, :url => admin_session_path, :method => :post do |f| %>
    2:   <ul class="form">
    3:   <% create_fields.each do |field| -%>
    4:     <li><%= field.render :create, controller, record %></li>
    5:   <% end -%>
    6:   </ul>
    7: 

```

**Comment by cs3b** [comment]
tracking deep:

``` ruby
    def render context, controller, *record_and_options
      options = record_and_options.extract_options!
      throw component
      component.process context, controller, record_and_options.first, options
    end
```

```
uncaught throw #<StringComponent:0x00000005f25f30 @_routes=nil, @_action_has_layout=true, @_view_context_class=nil, @field=email>
```

got

**Comment by cs3b** [comment]
could you point where actions :create, :update for string component are defined ?

as I mention in pull request on admin page I have error 500

But on edit / new pages for particular resources looks like working - when I'm lookin into source code then there is no action :create, :update. The only one that I see as good candidate is :form (and this works).

Litle lost in you code :-)

**Comment by pyromaniac** [comment]
:create and :update actions are not defined for base conponent, also their definitions are unnesessary until they are different.

Component actions should fallback the same way as controller's fieldsets - https://github.com/puffer/puffer/blob/master/lib/puffer/component.rb#L88

This means that if you try to render create action of component and create action is not defined, components will try to render form action, and only if form action missed - then should be raised exception.

**Comment by pyromaniac** [comment]
Ah! Gotcha!

replace this https://github.com/puffer/puffer/blob/master/app/controllers/puffer/sessions_base.rb#L10 by `define_fieldset :create, :fallbacks => :form` please. This should help. My bad. If it helps - please pull request it )

**Comment by cs3b** [comment]
closing - it's duplicate #25
