### ISSUE TITLE
search in mongoid fails when there is no field with type String

### ISSUE THREAD

**Issue by cs3b** [puffer/puffer#30]
it don't what to search for - maybe it shouldn't render form at all of there is no searchable field ?

**Comment by pyromaniac** [comment]
Hmhm. As a variant. It is really ambiguous situation.

**Comment by cs3b** [comment]
might be - but it's very hard to detect why it's failing unless you investigate mongo queries and look into puffer mongoid adapter

is a possibility to turn off search ?

**Comment by pyromaniac** [comment]
Yep, it is hard even for me lol. Ok, I'll hide field.
