### ISSUE TITLE
file upload fails

### ISSUE THREAD

**Issue by bartlomiejdanek** [puffer/puffer#32]
Missing `mulitpart="true"`

```
form do
  field :image, :type => :file
end
```

Or maybe is it any better way to upload files?

**Comment by pyromaniac** [comment]
I thought that rails sets mulitpart="true" authomaticly now. I'll check this. This is the only way now. But if you want better - just write your own upload component, with swf upload whatever.

**Comment by pyromaniac** [comment]
I've added multipart to forms. Check please.

**Comment by bartlomiejdanek** [comment]
Nice! Tested and it works, thank you!
