### ISSUE TITLE
current_puffer_user :_id

### ISSUE THREAD

**Issue by vladson** [puffer/puffer#36]
Могу ошибаться, но в методе current_puffer_user в  / lib / puffer / controller / auth.rb нужно убрать подчеркивание от id.
По крайней мере  у меня, пока не убрал подчеркивание от :_id бросал исключения

**Comment by pyromaniac** [comment]
Точно, спасибо. Я как-то не досмотрел. Можешь сделать патч?

**Comment by vladson** [comment]
Патч сделал (там изменений на 1 строчку), но я на github нуб, тебе куда его слать?

**Comment by pyromaniac** [comment]
кароче, сложно всё. Надо сначала сделать форк, склонировать его себе, локально пофиксить, запушить и сделать пулл-реквест. Первый и последний пункты делаются из интерфейса гитхаба. В общем, я щас сам пофиксю )

**Comment by vladson** [comment]
Ок, спасибо.  В след раз сделаю норм.

**Comment by pyromaniac** [comment]
Не за что. Сделал фикс, можешь апдейтиться.
