### ISSUE TITLE
belongs_to and puffer

### ISSUE THREAD

**Issue by proton** [puffer/puffer#37]
class Item < ActiveRecord::Base
    belongs_to :category
end

class Category < ActiveRecord::Base
    has_many :items
end

What shall I do to don't enter category_id manually?
# 

Как сделать так, чтобы не приходилось руками вбивать id категории? (Хочу получить либо красивый select, либо кнопку "Add Item" у категории.

**Comment by pyromaniac** [comment]
Да-да ) Я помню. У меня тут месячишко выдался очень загруженным. Надеюсь, что к выходным, а может и раньше, сделаю компоненты. Но если ассоциаций не очень много - можешь попробовать втупую:

`field :category_id, :select => proc{Category.all.map{|c| [c.name, c.id]}}`

Как-то так ) Очень надеюсь скоро выложить компоненты для селекта ассоциаций.

**Comment by proton** [comment]
Спасибо, буду ждать)

**Comment by Papipo** [comment]
What about mongoid?

Is it possible to have a "Select or add" field, or maybe an autocomplete field?

**Comment by pyromaniac** [comment]
Mongoid is supported fully, but choose components are not introduced yet. Will be soon, sorry

**Comment by Papipo** [comment]
Don't worry. So far puffer is the admin ui that has better mongoid support. It would be nice to have a roadmap with dates though :P

**Comment by pyromaniac** [comment]
Yes, would be nice, but i have only to hands and one head ) ASAP anyway.
