### ISSUE TITLE
rails g puffer:controller [MongoidModel] causes error: Undefined Method "to_adapter" for MongoidModel:Class

### ISSUE THREAD

**Issue by zben** [puffer/puffer#38]
Anyone knows what is going wrong here? I am using Rails 3.1 with Mongoid > 2.0.0. I am able to add AR models to puffer in the same app.

**Comment by pyromaniac** [comment]
At first, try to install puffer from master, please.

**Comment by pyromaniac** [comment]
I know! ) Try to define mongoid before puffer in your Gemfile. Should help.
