### ISSUE TITLE
Ошибка при rails g puffer_pages:install

### ISSUE THREAD

**Issue by greendog** [puffer/puffer#4]
Создал новое апп rails new puffer_pages
Поставил puffer_pages из этого репо в RAILS_ROOT/vendor/bundle/puffer_page
Сделал bundle install
Поставил puffer в RAILS_ROOT/vendor/bundle/puffer
Получилось так:
gem 'puffer_pages', :path => 'vendor/bundle/puffer_pages'
gem 'puffer', :path => 'vendor/bundle/puffer'

Делаю:
 rails g puffer_pages:install

вижу:

  /home/dev/puffer_pages/vendor/bundle/puffer_pages/lib/puffer_pages.rb:24: uninitialized constant Puffer (NameError)
  .................
  .................

**Comment by adie** [comment]
Не думал даже, но получилось воспроизвести)
Поставьте gem 'puffer' до gem 'puffer_pages' - и заработает.

**Comment by greendog** [comment]
Не. Всё-равно не работает:
 /home/greendog/.rvm/gems/ree-1.8.7-2010.02@main/gems/puffer_pages-0.0.7/lib/puffer_pages.rb:24: uninitialized constant Puffer (NameError)

**Comment by adie** [comment]
а bundle install выполнили после замены мест?
Мне конечно кажется странным что от перемены мест в Gemfile что-то должно менятся, но когда я поставил puffer_pages до puffer - у меня выпала эта ошибка.
Так что наверно тут где-то кроется баг

**Comment by greendog** [comment]
bundle install сделал конечно
сейчас ещё раз проверил - всё одно - не робит

**Comment by pyromaniac** [comment]
Кстати, да, сначала надо puffer, а потом уже puffer_pages.

**Comment by pyromaniac** [comment]
Баг пофиксил, спасибо за репорт.
