### ISSUE TITLE
a moth specs is failing

### ISSUE THREAD

**Issue by shiroginne** [puffer/puffer#40]
Month with failing travis_ci? LOKH!

**Comment by pyromaniac** [comment]
It's rspec-core bug. https://github.com/rspec/rspec-core/blob/master/Changelog.md Fixed in master, waiting for release.

**Comment by shiroginne** [comment]
what release? 2.8.0 released already :)

**Comment by pyromaniac** [comment]
R u stupid? 2.8.1 obviously.
