### ISSUE TITLE
undefined method `puffer' 

### ISSUE THREAD

**Issue by lagox** [puffer/puffer#42]
NoMethodError in Admin/jobs#index

undefined method `puffer' for /uploads/job/image/16/9783ac18b771b1ad449820473dce6afd.jpg:ImageUploader
Extracted source (around line #3):

1: <%# Here it should check file version mime and output image or link to file %>
2: <% if true %>
3:   <%= image_tag @record.send(field.name).send(thumbnail_name).url if @record.send("#{field.name}?") %>
4: <% else %>
5:   <%= link_to @record.send(field.name).send(thumbnail_name).url if @record.send("#{field.name}?") %>
6: <% end %>

Такая проблема. Юзаю rails 3.2.1, carrierwave

**Comment by pyromaniac** [comment]
А, ага. Надо либо сделать тумбу с именем :puffer, либо указать field :image, :thumbnail => :any_thumbnail_name

А так да, надо бы сделать варн или поадекватнее эксепшен. Спасибо.

**Comment by lagox** [comment]
Спасибо, помогло
